kind: Service
apiVersion: v1
metadata:
  name: portfolio-service
  namespace: portfolio
spec:
  selector:
    app: dev
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80
  type: ClusterIP  
